from pptx import Presentation
from pptx.util import Inches

# 1. Generate Content (using a placeholder for an LLM)
def generate_presentation_content():
    """
    This function simulates an LLM generating presentation content.
    In a real implementation, this would be a call to an LLM API.
    """
    return {
        "title": "My First AI-Generated Presentation",
        "subtitle": "A demonstration of the 'Custom Agents with LLMs' workflow",
        "slides": [
            {
                "title": "Slide 1: Introduction",
                "points": [
                    "This presentation was generated using a Python script.",
                    "The content was generated by a simulated LLM.",
                    "The presentation was created using the python-pptx library."
                ]
            },
            {
                "title": "Slide 2: The Workflow",
                "points": [
                    "Generate content using an LLM.",
                    "Use a script to create the presentation.",
                    "Refine and practice the presentation."
                ]
            }
        ]
    }

# 2. Create the Presentation
def create_presentation(content):
    """
    Creates a PowerPoint presentation from the given content.
    """
    prs = Presentation()

    # Add title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = content["title"]
    subtitle.text = content["subtitle"]

    # Add content slides
    for slide_content in content["slides"]:
        content_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(content_slide_layout)
        title = slide.shapes.title
        body = slide.shapes.placeholders[1]
        title.text = slide_content["title"]
        for point in slide_content["points"]:
            p = body.text_frame.add_paragraph()
            p.text = point
            p.level = 1

    return prs

# 3. Save the Presentation
if __name__ == "__main__":
    content = generate_presentation_content()
    prs = create_presentation(content)
    prs.save("my_presentation.pptx")
    print("Presentation 'my_presentation.pptx' created successfully.")
